/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: katrin.kor (https://sketchfab.com/katrin.701)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/magic-chest-e207de4b63d6458e95ae9079893f31ef
Title: magic chest
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/models/magic_chest.glb')
    const { actions } = useAnimations(animations, group)

    useFrame(() => {
        group.current.rotation.y += 0.010;
    })

    return (
        <group ref={group} {...props}
            dispose={null}
            scale={[0.15, 0.15, 0.15]}
            position={[0, -2.22, 0]}
        >
        <group name="Sketchfab_Scene">
            <group name="Object_5">
            <group name="unlock" />
            <group name="openTop" position={[0.01, 3.119, -4.1]} />
            </group>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh
            name="Object_8"
            geometry={nodes.Object_8.geometry}
            material={materials.gold}
            skeleton={nodes.Object_8.skeleton}
            />
            <skinnedMesh
            name="Object_10"
            geometry={nodes.Object_10.geometry}
            material={materials.gold}
            skeleton={nodes.Object_10.skeleton}
            />
            <skinnedMesh
            name="Object_11"
            geometry={nodes.Object_11.geometry}
            material={materials.wood}
            skeleton={nodes.Object_11.skeleton}
            />
            <skinnedMesh
            name="Object_13"
            geometry={nodes.Object_13.geometry}
            material={materials.gold}
            skeleton={nodes.Object_13.skeleton}
            />
            <skinnedMesh
            name="Object_15"
            geometry={nodes.Object_15.geometry}
            material={materials.gold}
            skeleton={nodes.Object_15.skeleton}
            />
            <skinnedMesh
            name="Object_17"
            geometry={nodes.Object_17.geometry}
            material={materials.wood}
            skeleton={nodes.Object_17.skeleton}
            />
            <skinnedMesh
            name="Object_18"
            geometry={nodes.Object_18.geometry}
            material={materials.gold}
            skeleton={nodes.Object_18.skeleton}
            />
            <skinnedMesh
            name="Object_19"
            geometry={nodes.Object_19.geometry}
            material={materials.diamond}
            skeleton={nodes.Object_19.skeleton}
            />
            {/* <mesh
            name="TABLE_TABLE1_0"
            castShadow
            receiveShadow
            geometry={nodes.TABLE_TABLE1_0.geometry}
            material={materials.TABLE1}
            /> */}
            <group name="particles_">
            <group name="crystal" position={[-0.009, 3.29, -0.295]} scale={[0.423, 0.517, 0.358]}>
                <mesh
                name="crystal_crystal_big1_0"
                castShadow
                receiveShadow
                geometry={nodes.crystal_crystal_big1_0.geometry}
                material={materials.crystal_big1}
                />
            </group>
            </group>
            <group name="particles33">
            <group
                name="particles1"
                position={[-2.135, 6.677, -0.394]}
                rotation={[1.942, -1.108, 1.267]}
                scale={0.27}>
                <mesh
                name="particles1_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles1_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles2"
                position={[0.496, 5.344, -0.352]}
                rotation={[-2.783, -0.921, -2.938]}
                scale={[0.165, 0.182, 0.165]}>
                <mesh
                name="particles2_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles2_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles15"
                position={[-2.877, 3.842, -0.681]}
                rotation={[-1.484, -0.753, -2.193]}
                scale={0.27}>
                <mesh
                name="particles15_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles15_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles34"
                position={[-0.623, 5.879, -1.394]}
                rotation={[-2.996, 0.131, 1.062]}
                scale={[0.357, 0.319, 0.357]}>
                <mesh
                name="particles34_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles34_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles35"
                position={[-1.889, 5.568, 1.978]}
                rotation={[3.067, -0.54, -0.623]}
                scale={[0.218, 0.215, 0.218]}>
                <mesh
                name="particles35_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles35_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles36"
                position={[-3.243, 3.814, 3.164]}
                rotation={[-0.542, -0.856, -2.47]}
                scale={[0.218, 0.215, 0.218]}>
                <mesh
                name="particles36_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles36_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles37"
                position={[-3.982, 5.664, 1.704]}
                rotation={[0.225, -0.44, -1.572]}
                scale={[0.357, 0.319, 0.357]}>
                <mesh
                name="particles37_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles37_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles38"
                position={[0.57, 1.273, -1.073]}
                rotation={[-0.555, -1.221, 0.852]}
                scale={[0.537, 0.48, 0.537]}>
                <mesh
                name="particles38_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles38_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles39"
                position={[-3.722, 2.126, -2.3]}
                rotation={[0.637, -1.087, -0.886]}
                scale={[0.813, 0.727, 0.813]}>
                <mesh
                name="particles39_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles39_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles40"
                position={[1.667, 1.944, -2.769]}
                rotation={[0.767, 1.071, -0.115]}
                scale={0.409}>
                <mesh
                name="particles40_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles40_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles41"
                position={[0.689, 4.497, 1.551]}
                rotation={[2.075, -0.143, -1.877]}
                scale={[0.25, 0.275, 0.25]}>
                <mesh
                name="particles41_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles41_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles42"
                position={[2.186, 2.817, -1.992]}
                rotation={[-2.945, 0.393, -1.151]}
                scale={[0.25, 0.275, 0.25]}>
                <mesh
                name="particles42_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles42_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles43"
                position={[-1.411, 4.101, -0.628]}
                rotation={[-1.153, -1.248, -1.585]}
                scale={0.409}>
                <mesh
                name="particles43_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles43_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles44"
                position={[-0.546, 4.56, 1.85]}
                rotation={[-1.295, -0.336, 1.613]}
                scale={[0.541, 0.484, 0.541]}>
                <mesh
                name="particles44_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles44_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles45"
                position={[-3.042, 3.932, 0.359]}
                rotation={[-0.986, -1.037, 1.684]}
                scale={[0.331, 0.326, 0.331]}>
                <mesh
                name="particles45_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles45_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles46"
                position={[2.584, 3.884, -0.161]}
                rotation={[-1.927, 0.991, 2.797]}
                scale={[0.331, 0.326, 0.331]}>
                <mesh
                name="particles46_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles46_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles47"
                position={[-1.754, 5.34, -2.041]}
                rotation={[2.392, -0.738, 0.899]}
                scale={[0.541, 0.484, 0.541]}>
                <mesh
                name="particles47_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles47_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles48"
                position={[-0.946, 2.455, -1.809]}
                rotation={[-0.347, 0.082, 1.579]}
                scale={[0.813, 0.727, 0.813]}>
                <mesh
                name="particles48_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles48_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles49"
                position={[-3.782, 6.411, 0.032]}
                rotation={[0.661, -0.757, 1.825]}
                scale={[0.813, 0.727, 0.813]}>
                <mesh
                name="particles49_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles49_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles50"
                position={[-3.921, 1.177, -0.883]}
                rotation={[-0.465, -0.391, -2.848]}
                scale={[0.813, 0.727, 0.813]}>
                <mesh
                name="particles50_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles50_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles51"
                position={[-0.998, 5.312, -1.855]}
                rotation={[-0.401, -0.468, -0.997]}
                scale={[1.33, 1.19, 1.33]}>
                <mesh
                name="particles51_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles51_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles52"
                position={[0.094, 1.744, -0.273]}
                rotation={[-2.658, -0.297, -2.897]}
                scale={[0.542, 0.533, 0.542]}>
                <mesh
                name="particles52_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles52_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles53"
                position={[1.089, 3.401, 0.468]}
                rotation={[1.607, 1.301, 2.764]}
                scale={0.669}>
                <mesh
                name="particles53_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles53_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles54"
                position={[-1.612, 6.128, 0.437]}
                rotation={[2.01, -0.367, 1.304]}
                scale={[0.885, 0.792, 0.885]}>
                <mesh
                name="particles54_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles54_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles55"
                position={[-3.341, 3.612, 1.662]}
                rotation={[-0.033, -0.085, -0.498]}
                scale={[0.41, 0.451, 0.41]}>
                <mesh
                name="particles55_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles55_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles57"
                position={[-1.722, 3.347, 2.398]}
                rotation={[-2.009, -0.557, 2.666]}
                scale={0.669}>
                <mesh
                name="particles57_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles57_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles58"
                position={[4.005, 3.656, 1.403]}
                rotation={[-1.306, -0.516, -0.134]}
                scale={[0.41, 0.451, 0.41]}>
                <mesh
                name="particles58_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles58_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles59"
                position={[-3.133, 1.652, -1.133]}
                rotation={[0.305, 0.155, 0.776]}
                scale={[1.33, 1.19, 1.33]}>
                <mesh
                name="particles59_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles59_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles60"
                position={[-0.029, 4.157, 1.921]}
                rotation={[-1.793, 0.173, 1.523]}
                scale={[0.885, 0.792, 0.885]}>
                <mesh
                name="particles60_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles60_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles61"
                position={[2.777, 4.026, -0.554]}
                rotation={[-2.626, 1.326, -0.662]}
                scale={[0.542, 0.533, 0.542]}>
                <mesh
                name="particles61_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles61_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles62"
                position={[0.098, 4.394, -2.67]}
                rotation={[0.737, 0.911, 0.209]}
                scale={[1.33, 1.19, 1.33]}>
                <mesh
                name="particles62_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles62_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles63"
                position={[-3.963, 3.227, -2.313]}
                rotation={[-0.724, 1.016, 2.796]}
                scale={0.442}>
                <mesh
                name="particles63_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles63_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles64"
                position={[-0.629, 6.14, 0.896]}
                rotation={[-2.225, 0.012, -2.557]}
                scale={[1.173, 1.19, 1.173]}>
                <mesh
                name="particles64_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles64_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles65"
                position={[3.776, 4.917, 2.244]}
                rotation={[0.861, -0.367, -1.632]}
                scale={[0.27, 0.297, 0.27]}>
                <mesh
                name="particles65_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles65_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles66"
                position={[-4.013, 4.335, 2.256]}
                rotation={[1.636, 0.357, 2.62]}
                scale={[0.27, 0.297, 0.27]}>
                <mesh
                name="particles66_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles66_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles67"
                position={[2.414, 1.132, -2.645]}
                rotation={[-1.166, -1.447, -0.887]}
                scale={0.442}>
                <mesh
                name="particles67_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles67_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles68"
                position={[1.24, 5.147, -1.756]}
                rotation={[1.661, -0.491, 1.369]}
                scale={[0.584, 0.523, 0.584]}>
                <mesh
                name="particles68_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles68_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles69"
                position={[-2.434, 2.67, -3.043]}
                rotation={[-1.241, 0.056, -1.339]}
                scale={[0.358, 0.352, 0.358]}>
                <mesh
                name="particles69_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles69_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles70"
                position={[2.659, 2.231, 0.586]}
                rotation={[-2.749, -0.709, -0.344]}
                scale={[0.358, 0.352, 0.358]}>
                <mesh
                name="particles70_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles70_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles71"
                position={[0.483, 1.323, -2.598]}
                rotation={[2.507, 0.615, -2.312]}
                scale={[0.584, 0.523, 0.584]}>
                <mesh
                name="particles71_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles71_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles72"
                position={[-1.883, 5.134, -1.284]}
                rotation={[-1.789, 0.802, 0.076]}
                scale={[0.541, 0.484, 0.541]}>
                <mesh
                name="particles72_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles72_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles73"
                position={[-2.709, 5.875, -2.129]}
                rotation={[2.811, -0.215, 2.806]}
                scale={[0.165, 0.182, 0.165]}>
                <mesh
                name="particles73_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles73_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles74"
                position={[-1.071, 3.236, 1.076]}
                rotation={[1.984, -1.193, -2.156]}
                scale={[0.165, 0.182, 0.165]}>
                <mesh
                name="particles74_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles74_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles75"
                position={[0.042, 4.26, -1.403]}
                rotation={[2.981, -0.564, -2.29]}
                scale={0.27}>
                <mesh
                name="particles75_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles75_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles76"
                position={[2.326, 3.723, -0.616]}
                rotation={[3.064, 0.402, -2.063]}
                scale={[0.357, 0.319, 0.357]}>
                <mesh
                name="particles76_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles76_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles77"
                position={[2.255, 1.198, -1.189]}
                rotation={[1.458, -0.406, 3.038]}
                scale={[0.218, 0.215, 0.218]}>
                <mesh
                name="particles77_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles77_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles78"
                position={[3.768, 5.058, 1.458]}
                rotation={[1.557, 0.732, 0.489]}
                scale={[0.218, 0.215, 0.218]}>
                <mesh
                name="particles78_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles78_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles79"
                position={[-0.1, 5.201, -0.149]}
                rotation={[3.104, 1.221, -2.623]}
                scale={[0.357, 0.319, 0.357]}>
                <mesh
                name="particles79_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles79_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles80"
                position={[1.384, 4.314, -0.359]}
                rotation={[-1.898, 1, 1.816]}
                scale={[1.134, 1.015, 1.134]}>
                <mesh
                name="particles80_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles80_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles81"
                position={[2.96, 5.741, -0.354]}
                rotation={[-1.721, 1.072, 1.72]}
                scale={[0.815, 0.729, 0.815]}>
                <mesh
                name="particles81_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles81_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles82"
                position={[2.907, 2.169, 0.384]}
                rotation={[-2.474, -0.802, 2.617]}
                scale={[0.725, 0.819, 0.745]}>
                <mesh
                name="particles82_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles82_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles83"
                position={[-1.376, 1.553, 0.056]}
                rotation={[2.351, -0.141, 0.959]}
                scale={[0.377, 0.415, 0.377]}>
                <mesh
                name="particles83_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles83_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles84"
                position={[-2.932, 1.299, -2.65]}
                rotation={[2.265, 0.386, -1.744]}
                scale={[0.948, 0.727, 0.948]}>
                <mesh
                name="particles84_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles84_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles85"
                position={[-2.284, 4.483, -1.138]}
                rotation={[2.205, -0.065, 1.492]}
                scale={[0.386, 0.326, 0.386]}>
                <mesh
                name="particles85_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles85_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles86"
                position={[-0.881, 1.591, 0.374]}
                rotation={[0.359, 0.096, -0.731]}
                scale={[0.477, 0.409, 0.477]}>
                <mesh
                name="particles86_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles86_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles87"
                position={[-1.318, 4.784, -2.734]}
                rotation={[-0.113, -0.075, -2.495]}
                scale={[0.631, 0.484, 0.631]}>
                <mesh
                name="particles87_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles87_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles88"
                position={[1.217, 4.73, 1.042]}
                rotation={[-3.041, -0.339, -2.999]}
                scale={[0.292, 0.275, 0.292]}>
                <mesh
                name="particles88_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles88_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles89"
                position={[-0.053, 1.298, -1.768]}
                rotation={[-0.337, -0.429, 0.601]}
                scale={[0.625, 0.48, 0.625]}>
                <mesh
                name="particles89_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles89_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles90"
                position={[2.835, 5.043, 0.965]}
                rotation={[-0.138, -0.623, -0.103]}
                scale={[0.477, 0.409, 0.477]}>
                <mesh
                name="particles90_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles90_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles91"
                position={[2.319, 2.032, -1.812]}
                rotation={[-2.492, -0.312, -2.406]}
                scale={[0.292, 0.275, 0.292]}>
                <mesh
                name="particles91_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles91_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles92"
                position={[-3.431, 5.84, 1.11]}
                rotation={[-1.145, -0.1, -0.165]}
                scale={[0.948, 0.727, 0.948]}>
                <mesh
                name="particles92_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles92_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles93"
                position={[-1.689, 5.321, -2.327]}
                rotation={[-1.228, -0.401, -2.432]}
                scale={[0.631, 0.484, 0.631]}>
                <mesh
                name="particles93_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles93_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles94"
                position={[3.412, 4.473, 2.217]}
                rotation={[-0.608, -0.045, -3.019]}
                scale={[0.386, 0.326, 0.386]}>
                <mesh
                name="particles94_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles94_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles95"
                position={[-1.034, 3.115, -2.45]}
                rotation={[1.601, -0.199, 0.085]}
                scale={[0.416, 0.319, 0.416]}>
                <mesh
                name="particles95_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles95_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles96"
                position={[1.998, 4.481, -1.187]}
                rotation={[1.744, 0.737, 1.085]}
                scale={[0.255, 0.215, 0.255]}>
                <mesh
                name="particles96_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles96_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles97"
                position={[2.458, 1.226, 0.372]}
                rotation={[2.587, -0.445, 0.78]}
                scale={[0.255, 0.215, 0.255]}>
                <mesh
                name="particles97_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles97_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles98"
                position={[1.646, 5.596, 0.096]}
                rotation={[-1.043, -0.356, 1.122]}
                scale={[0.416, 0.319, 0.416]}>
                <mesh
                name="particles98_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles98_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles100"
                position={[-0.53, 1.879, -2.349]}
                rotation={[-2.77, 0.031, 0.727]}
                scale={[0.315, 0.27, 0.315]}>
                <mesh
                name="particles100_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles100_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles101"
                position={[1.161, 2.864, 2.711]}
                rotation={[-0.742, -0.938, -2.848]}
                scale={[0.948, 0.727, 0.948]}>
                <mesh
                name="particles101_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles101_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles102"
                position={[0.414, 2.345, 1.06]}
                rotation={[-2.202, 0.984, -1.735]}
                scale={[0.193, 0.182, 0.193]}>
                <mesh
                name="particles102_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles102_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles103"
                position={[0.587, 2.151, 0.067]}
                rotation={[-0.234, -0.802, -2.338]}
                scale={[0.44, 0.415, 0.44]}>
                <mesh
                name="particles103_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles103_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles104"
                position={[1.627, 2.011, 1.705]}
                rotation={[1.085, -0.651, -0.452]}
                scale={[0.845, 0.819, 0.868]}>
                <mesh
                name="particles104_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles104_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles105"
                position={[0.146, 2.239, -2.447]}
                rotation={[-2.052, -1.303, 0.444]}
                scale={[0.95, 0.729, 0.95]}>
                <mesh
                name="particles105_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles105_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles106"
                position={[2.014, 3.163, 0.675]}
                rotation={[-3.059, 0.485, -1.527]}
                scale={[1.322, 1.015, 1.322]}>
                <mesh
                name="particles106_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles106_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles107"
                position={[1.153, 4.839, -2.405]}
                rotation={[0.233, -1.1, 2.635]}
                scale={[0.315, 0.27, 0.315]}>
                <mesh
                name="particles107_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles107_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles108"
                position={[-3.855, 3.81, -3.085]}
                rotation={[0.073, 0.199, -2.489]}
                scale={[0.193, 0.182, 0.193]}>
                <mesh
                name="particles108_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles108_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles110"
                position={[2.031, 5.222, 2.044]}
                rotation={[2.598, -0.665, -0.143]}
                scale={[0.631, 0.484, 0.631]}>
                <mesh
                name="particles110_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles110_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles111"
                position={[-2.681, 5.326, -0.186]}
                rotation={[-1.009, 0.997, -2.489]}
                scale={[1.551, 1.19, 1.551]}>
                <mesh
                name="particles111_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles111_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles112"
                position={[1.674, 5.123, 0.333]}
                rotation={[-0.505, 0.698, 1.356]}
                scale={[0.477, 0.451, 0.477]}>
                <mesh
                name="particles112_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles112_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles113"
                position={[-1.802, 2.167, -2.585]}
                rotation={[-0.864, -0.651, 2.415]}
                scale={[0.78, 0.669, 0.78]}>
                <mesh
                name="particles113_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles113_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles114"
                position={[-3.047, 1.89, -2.121]}
                rotation={[0.921, -0.49, -0.9]}
                scale={[1.023, 0.785, 1.023]}>
                <mesh
                name="particles114_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles114_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles116"
                position={[-3.604, 4.489, -1.097]}
                rotation={[1.426, -0.19, 2.602]}
                scale={[1.032, 0.792, 1.032]}>
                <mesh
                name="particles116_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles116_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles117"
                position={[2.699, 5.998, -1.794]}
                rotation={[0.774, 0.57, 2.911]}
                scale={[0.78, 0.669, 0.78]}>
                <mesh
                name="particles117_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles117_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles118"
                position={[-4.054, 1.031, 1.69]}
                rotation={[-0.182, -0.976, -0.288]}
                scale={[0.631, 0.533, 0.631]}>
                <mesh
                name="particles118_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles118_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles119"
                position={[-0.186, 1.924, 0.266]}
                rotation={[-0.316, -0.419, 1.183]}
                scale={[1.551, 1.19, 1.551]}>
                <mesh
                name="particles119_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles119_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles120"
                position={[-3.906, 2.354, 1.579]}
                rotation={[-0.218, -1.089, 1.827]}
                scale={[0.193, 0.182, 0.193]}>
                <mesh
                name="particles120_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles120_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles121"
                position={[-2.232, 6.39, 0.607]}
                rotation={[-3.128, -1.35, 2.927]}
                scale={[0.315, 0.27, 0.315]}>
                <mesh
                name="particles121_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles121_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles122"
                position={[-3.143, 1.029, 2.723]}
                rotation={[-2.014, -0.923, -2.791]}
                scale={[0.681, 0.523, 0.681]}>
                <mesh
                name="particles122_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles122_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles123"
                position={[1.18, 5.429, -1.255]}
                rotation={[-0.094, 0.384, 1.599]}
                scale={[0.417, 0.352, 0.417]}>
                <mesh
                name="particles123_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles123_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles124"
                position={[-3.733, 1.799, 1.908]}
                rotation={[2.32, 0.11, -2.758]}
                scale={[0.417, 0.352, 0.417]}>
                <mesh
                name="particles124_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles124_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles125"
                position={[-2.501, 5.492, -0.984]}
                rotation={[0.784, -1.075, 1.073]}
                scale={[0.681, 0.523, 0.681]}>
                <mesh
                name="particles125_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles125_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles126"
                position={[-0.655, 4.58, 0.485]}
                rotation={[-3.005, -0.14, 3.015]}
                scale={[0.515, 0.442, 0.515]}>
                <mesh
                name="particles126_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles126_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles127"
                position={[-4.089, 1.17, 2.633]}
                rotation={[0.046, -0.143, -2.625]}
                scale={[0.315, 0.297, 0.315]}>
                <mesh
                name="particles127_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles127_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles128"
                position={[-3.723, 2.902, 1.993]}
                rotation={[-1.507, -0.034, 1.487]}
                scale={[0.315, 0.297, 0.315]}>
                <mesh
                name="particles128_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles128_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles129"
                position={[3.001, 1.629, 1.86]}
                rotation={[0.402, 0.967, -1.001]}
                scale={[1.551, 1.19, 1.551]}>
                <mesh
                name="particles129_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles129_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles130"
                position={[3.15, 3.732, -3.248]}
                rotation={[1.117, 0.652, 1.442]}
                scale={[0.515, 0.442, 0.515]}>
                <mesh
                name="particles130_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles130_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles131"
                position={[-3.286, 5.515, 1.538]}
                rotation={[-1.046, 0.776, -1.997]}
                scale={[1.551, 1.19, 1.551]}>
                <mesh
                name="particles131_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles131_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles132"
                position={[1.583, 6.067, 0.91]}
                rotation={[-1.929, 0.383, -1.864]}
                scale={[0.631, 0.533, 0.631]}>
                <mesh
                name="particles132_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles132_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles133"
                position={[-3.441, 1.338, 2.057]}
                rotation={[-2.108, -0.221, -0.671]}
                scale={[1.032, 0.792, 1.032]}>
                <mesh
                name="particles133_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles133_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles134"
                position={[-3.989, 5.335, 2.481]}
                rotation={[-0.932, -1.295, 1.809]}
                scale={[0.416, 0.319, 0.416]}>
                <mesh
                name="particles134_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles134_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles135"
                position={[2.229, 5.685, -2.382]}
                rotation={[2.019, -0.576, 0.749]}
                scale={[0.255, 0.215, 0.255]}>
                <mesh
                name="particles135_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles135_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles136"
                position={[-2.864, 4.861, 2.358]}
                rotation={[1.42, -0.019, 2.362]}
                scale={[0.255, 0.215, 0.255]}>
                <mesh
                name="particles136_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles136_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            <group
                name="particles137"
                position={[-2.797, 3.048, -3.079]}
                rotation={[1.034, -0.516, 2.359]}
                scale={[0.416, 0.319, 0.416]}>
                <mesh
                name="particles137_crystal1_0"
                castShadow
                receiveShadow
                geometry={nodes.particles137_crystal1_0.geometry}
                material={materials.crystal1}
                />
            </group>
            </group>
        </group>
        </group>
    )
}

useGLTF.preload('/models/magic_chest.glb')