/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: wellintonfarias (https://sketchfab.com/wellintonfarias)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cetrocajado-magico-scepterwand-f273753490514c2985d42be7a2c1c883
Title: Cetro/Cajado Mágico - Scepter/Wand
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
    const { nodes, materials } = useGLTF('/models/cetrocajado_magico_-_scepterwand.glb')

    const modelRef = useRef();

    useFrame(() => {
        modelRef.current.rotation.y += 0.010;
    })

    return (
        <group {...props}
            dispose={null}
            scale={[3.5, 3.5, 3.5]}
            position={[0, -2, 0]}
            ref={modelRef}
        >
        <group position={[-81.848, 0, 30.621]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[-40.925, 17.356, -13.603]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                castShadow
                receiveShadow
                geometry={nodes['Cone016_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[0.288, -0.194, -0.356]}
                rotation={[2.221, 0.447, -2.711]}
                scale={0.48}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes['Cone011_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[0.483, -0.205, -0.059]}
                rotation={[1.682, 0.763, -1.817]}
                scale={0.48}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes['Cone015_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[0.357, -0.191, 0.287]}
                rotation={[1.029, 0.577, -0.822]}
                scale={0.48}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes['Cone009_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[0.039, -0.175, 0.476]}
                rotation={[0.804, 0.08, -0.169]}
                scale={0.48}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes['Cone014_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[-0.313, -0.183, 0.372]}
                rotation={[0.921, -0.447, 0.431]}
                scale={0.48}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes['Cone012_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[-0.483, -0.176, 0.033]}
                rotation={[1.46, -0.763, 1.325]}
                scale={0.48}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes['Cone013_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[-0.35, -0.201, -0.29]}
                rotation={[2.113, -0.577, 2.319]}
                scale={0.48}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes['Cone010_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[-0.05, -0.169, -0.476]}
                rotation={[2.337, -0.08, 2.972]}
                scale={0.48}
                />
            </group>
            <group
                position={[-40.943, 17.343, 6.728]}
                rotation={[0, 0, 3.054]}
                scale={[-1, 1, 0.903]}>
                <mesh
                castShadow
                receiveShadow
                geometry={nodes['Helix002_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[0, 0, -19.258]}
                />
            </group>
            <group position={[-40.943, 17.343, 6.732]} scale={[-1, 1, 0.903]}>
                <mesh
                castShadow
                receiveShadow
                geometry={nodes['Helix001_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[0, 0, -19.258]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Cylinder004_Material_#24_0'].geometry}
                material={materials.Material_24}
                position={[-40.932, 17.354, 26.735]}
                rotation={[Math.PI, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Cylinder005_Material_#26_0'].geometry}
                material={materials.Material_26}
                position={[-40.929, 17.361, 27.27]}
                scale={[0.076, 0.075, 0.273]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Pyramid018_Material_#26_0'].geometry}
                material={materials.Material_26}
                position={[-40.949, 17.338, -12.937]}
                rotation={[-3.132, 0.012, 0.025]}
                scale={[0.155, 0.155, 0.245]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere023_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[-40.929, 17.349, -12.158]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere024_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[-40.929, 17.361, 26.47]}
                rotation={[-Math.PI, 0, 0]}
                scale={1.438}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere025_Material_#28_0'].geometry}
                material={materials.Material_28}
                position={[-40.929, 17.361, 28.132]}
                rotation={[-Math.PI, 0, 0]}
                scale={3.187}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere026_Material_#28_0'].geometry}
                material={materials.Material_28}
                position={[-40.929, 17.361, 27.381]}
                rotation={[-Math.PI, 0, 0]}
                scale={1.981}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere030_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[-40.929, 17.361, 26.752]}
                scale={[1.285, 1.285, 0.912]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere034_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[-40.929, 17.349, 25.234]}
                scale={[0.835, 0.835, 0.422]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere035_Material_#27_0'].geometry}
                material={materials.Material_27}
                position={[-40.929, 17.349, 25.716]}
                scale={[0.827, 0.827, 1.076]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere036_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[-40.929, 17.349, 24.656]}
                scale={[0.835, 0.835, 0.422]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere037_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[-40.929, 17.349, -10.717]}
                scale={[0.867, 0.867, 0.438]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere038_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[-40.929, 17.349, 24.147]}
                scale={[0.874, 0.874, 0.442]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere040_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[-40.929, 17.349, 26.158]}
                scale={[0.835, 0.835, 0.422]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere041_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[-40.929, 17.349, -12.278]}
                scale={[0.835, 0.835, 0.422]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere042_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[-40.929, 17.349, -11.398]}
                scale={[0.835, 0.835, 0.422]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere043_Material_#27_0'].geometry}
                material={materials.Material_27}
                position={[-40.929, 17.349, -11.815]}
                scale={[0.867, 0.867, 0.811]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere044_Material_#28_0'].geometry}
                material={materials.Material_28}
                position={[-40.929, 17.361, 29.885]}
                rotation={[-Math.PI, 0, 0]}
                scale={10.401}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Pyramid014_Material_#26_0'].geometry}
                material={materials.Material_26}
                position={[-40.909, 17.736, 26.569]}
                rotation={[-0.873, 0, -Math.PI / 2]}
                scale={0.555}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Pyramid012_Material_#26_0'].geometry}
                material={materials.Material_26}
                position={[-41.238, 17.546, 26.569]}
                rotation={[-0.537, -0.725, -0.732]}
                scale={0.555}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Pyramid017_Material_#26_0'].geometry}
                material={materials.Material_26}
                position={[-41.253, 17.196, 26.569]}
                rotation={[0.467, -0.767, 0.628]}
                scale={0.555}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Pyramid015_Material_#26_0'].geometry}
                material={materials.Material_26}
                position={[-40.909, 16.977, 26.569]}
                rotation={[0.873, 0, Math.PI / 2]}
                scale={0.555}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Pyramid016_Material_#26_0'].geometry}
                material={materials.Material_26}
                position={[-40.566, 17.517, 26.569]}
                rotation={[-0.467, 0.767, -2.514]}
                scale={0.555}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Pyramid013_Material_#26_0'].geometry}
                material={materials.Material_26}
                position={[-40.581, 17.167, 26.569]}
                rotation={[0.537, 0.725, 2.41]}
                scale={0.555}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere045_Material_#29_0'].geometry}
                material={materials.Material_29}
                position={[-40.924, 17.194, 35.764]}
                rotation={[Math.PI, 0, 2.88]}
                scale={[1.026, 1.056, 2.238]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Sphere046_Material_#29_0'].geometry}
                material={materials.Material_29}
                position={[-40.924, 17.194, 29.95]}
                scale={[0.733, 0.733, 1.048]}
            />
            </group>
        </group>
        </group>
    )
}

useGLTF.preload('/models/cetrocajado_magico_-_scepterwand.glb')