/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Meee (https://sketchfab.com/Meee)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/wizards-cane-1b54a0de0dfb4946836635db1ec446ca
Title: Wizard's Cane
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
    const { nodes, materials } = useGLTF('/models/wizards_cane.glb')

    const modelRef = useRef();

    useFrame(() => {
        modelRef.current.rotation.y += 0.010;
    })

    return (
        <group {...props}
            dispose={null}
            scale={[3.5, 3.5, 3.5]}
            position={[0, 0.75, 0]}
            ref={modelRef}
        >
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_2.geometry}
            material={materials['Scene_-_Root']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.054}
        />
        </group>
    )
}

useGLTF.preload('/models/wizards_cane.glb')