/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Brad Groatman (https://sketchfab.com/groatman)
License: SKETCHFAB Editorial (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/wizard-f6338ab3fbbb4550b4b0240446b31e24
Title: Wizard
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Wizard2(props) {
    const { nodes, materials } = useGLTF('/models/wizard.glb')

    const modelRef = useRef();

    useFrame((state, delta, xrFrame) => {
        modelRef.current.position.y = -3.5 + Math.sin(state.clock.elapsedTime) * 0.15;
    });

    return (
        <group {...props}
            dispose={null}
            ref={modelRef}
            position={[-0.08, 0, 0.05]}
            scale={[0.275, 0.275, 0.275]}
            rotation={[0.2, -0.15, 0]}
        >
        {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.base1ZBrushPolyMesh3D_baseMAT_0.geometry}
            material={materials.baseMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        /> */}
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.ChainsZBrushPolyMesh3D_gold_0.geometry}
            material={materials.PaletteMaterial001}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.CollarZBrushPolyMesh3D_collarMAT_0.geometry}
            material={materials.collarMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.EyebrowsZBrushPolyMesh3D_eyebrowMAT_0.geometry}
            material={materials.eyebrowMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.EyelashesZBrushPolyMesh3D_black_0.geometry}
            material={materials.PaletteMaterial002}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.EyesZBrushPolyMesh3D_eyeMAT_0.geometry}
            material={materials.eyeMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.FaceZBrushPolyMesh3D_faceMAT_0.geometry}
            material={materials.faceMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.Fibers36ZBrushPolyMesh3D_fiberMAT_0.geometry}
            material={materials.fiberMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        /> */}
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Hair1ZBrushPolyMesh3D_hair1MAT_0.geometry}
            material={materials.hair1MAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Hair2ZBrushPolyMesh3D_hair2MAT_0.geometry}
            material={materials.hair2MAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.HatZBrushPolyMesh3D_hatMAT_0.geometry}
            material={materials.hatMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.HatBrimZBrushPolyMesh3D_hatbrimMAT_0.geometry}
            material={materials.hatbrimMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.LanternRIvetsZBrushPolyMesh3D_silver_0.geometry}
            material={materials.PaletteMaterial003}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.LeftHandZBrushPolyMesh3D_lefthandMAT_0.geometry}
            material={materials.lefthandMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.MoustacheZBrushPolyMesh3D_moustacheMAT_0.geometry}
            material={materials.moustacheMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.RightHandZBrushPolyMesh3D_rightHandMAT_0.geometry}
            material={materials.rightHandMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.RobeZBrushPolyMesh3D_robeMAT_0.geometry}
            material={materials.robeMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.StaffZBrushPolyMesh3D_staffMAT_0.geometry}
            material={materials.staffMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.StaffVineZBrushPolyMesh3D_staffvineMAT_0.geometry}
            material={materials.staffvineMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.TorsoZBrushPolyMesh3D_torsoMAT_0.geometry}
            material={materials.torsoMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.VestZBrushPolyMesh3D_vestMAT_0.geometry}
            material={materials.vestMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.VestFlapsZBrushPolyMesh3D_vestflapMAT_0.geometry}
            material={materials.vestflapMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.swooshZBrushPolyMesh3D_swooshMAT_0.geometry}
            material={materials.PaletteMaterial004}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.LanternGlobe1ZBrushPolyMesh3D_globeMAT1_0.geometry}
            material={materials.globeMAT1}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.SashZBrushPolyMesh3D_sashMAT_0.geometry}
            material={materials.sashMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.SashPartsZBrushPolyMesh3D_sasphartsMAT_0.geometry}
            material={materials.sasphartsMAT}
            position={[-1.067, 46.716, 2.97]}
            scale={3.632}
        />
        </group>
    )
}

useGLTF.preload('/models/wizard.glb')
